[build]
  publish = "src"
  command = "npm run build"

[[redirects]]
  from = "/"
  to = "/components/ui/inicio.html"
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/index.html"
  status = 200