[build]
  publish = "src"
  command = ""

[[redirects]]
  from = "/"
  to = "/components/ui/inicio.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/pages/Index.tsx"
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/pages/Index.tsx"
  status = 200